[features]
seeds = false
skip-lint = false

[programs.localnet]
tic_tac_toe = "C59WuiXLLrTrE6dk2ECZ7pKv4QC64uM3QfiEYxhMVhuV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/park/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
